-- Run in the Supabase SQL editor. Teacher accounts are promoted by an administrator only.
create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users on delete cascade, display_name text not null default '', role text not null default 'student' check(role in ('student','teacher')), created_at timestamptz not null default now());
create table if not exists public.classes(id uuid primary key default gen_random_uuid(), name text not null, class_code text, invite_code text not null unique default upper(substr(encode(gen_random_bytes(8),'hex'),1,8)), teacher_id uuid not null references public.profiles(id), created_at timestamptz not null default now());
alter table public.classes add column if not exists class_code text;
create unique index if not exists classes_class_code_unique on public.classes(class_code) where class_code is not null;
create table if not exists public.class_members(class_id uuid references public.classes on delete cascade, student_id uuid references public.profiles on delete cascade, created_at timestamptz not null default now(), primary key(class_id,student_id));
create table if not exists public.progress(student_id uuid primary key references public.profiles on delete cascade, state jsonb not null, revision bigint not null default 0, updated_at timestamptz not null default now());
create table if not exists public.teacher_comments(class_id uuid references public.classes on delete cascade, student_id uuid references public.profiles on delete cascade, teacher_id uuid not null default auth.uid() references public.profiles(id), body text not null check(length(body)<=2000), updated_at timestamptz not null default now(), primary key(class_id,student_id));
create or replace function public.save_student_progress(payload jsonb,client_revision bigint,client_updated_at timestamptz) returns void language plpgsql security definer set search_path=public as $$ begin insert into progress(student_id,state,revision,updated_at) values(auth.uid(),payload,client_revision,client_updated_at) on conflict(student_id) do update set state=excluded.state,revision=excluded.revision,updated_at=excluded.updated_at where excluded.revision>=progress.revision; end $$;
create or replace function public.is_teacher_of(target uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from classes where id=target and teacher_id=auth.uid()) $$;
drop function if exists public.create_class(text);
create or replace function public.create_class(class_name text,requested_class_code text) returns jsonb language plpgsql security definer set search_path=public as $$ declare c classes; begin if coalesce((select role from profiles where id=auth.uid()),'') <> 'teacher' then raise exception 'teacher only'; end if; if coalesce(requested_class_code,'') !~ '^[0-9]{3}$' then raise exception 'class code must be three digits'; end if; insert into classes(name,class_code,teacher_id) values(left(trim(class_name),100),requested_class_code,auth.uid()) returning * into c; return jsonb_build_object('id',c.id,'name',c.name,'class_code',c.class_code); end $$;
create or replace function public.join_class(requested_code text) returns void language plpgsql security definer set search_path=public as $$ declare c classes; begin select * into c from classes where classes.invite_code=upper(trim(requested_code)); if c.id is null then raise exception 'invalid class code'; end if; insert into class_members(class_id,student_id) values(c.id,auth.uid()) on conflict do nothing; end $$;
create or replace function public.join_class_by_code(requested_class_code text) returns void language plpgsql security definer set search_path=public as $$ declare target_class uuid; begin if coalesce((select role from profiles where id=auth.uid()),'') <> 'student' then raise exception 'student account required'; end if; select id into target_class from classes where class_code=requested_class_code; if target_class is null then raise exception 'class not found; ask your teacher to create this three-digit class'; end if; insert into class_members(class_id,student_id) values(target_class,auth.uid()) on conflict do nothing; end $$;
create or replace function public.class_leaderboard(target_class uuid) returns table(student_id uuid,display_name text,score numeric,completed boolean,updated_at timestamptz) language sql stable security definer set search_path=public as $$ select p.id,p.display_name,coalesce((g.state->'metrics'->>'score')::numeric,0),coalesce((g.state->'state'->>'completed')::boolean,false),g.updated_at from class_members m join profiles p on p.id=m.student_id left join progress g on g.student_id=p.id where m.class_id=target_class and (m.student_id=auth.uid() or exists(select 1 from class_members mine where mine.class_id=target_class and mine.student_id=auth.uid())) order by 3 desc,5 asc $$;
-- Dashboard RPC returns member state summary and teacher feedback; access requires class ownership.
create or replace function public.teacher_class_progress(target_class uuid) returns table(student_id uuid,display_name text,state jsonb,updated_at timestamptz,teacher_comment text) language plpgsql stable security definer set search_path=public as $$ begin if not is_teacher_of(target_class) then raise exception 'teacher only'; end if; return query select p.id,p.display_name,g.state,g.updated_at,c.body from class_members m join profiles p on p.id=m.student_id left join progress g on g.student_id=p.id left join teacher_comments c on c.student_id=p.id and c.class_id=target_class where m.class_id=target_class order by p.display_name; end $$;
create or replace function public.bootstrap_profile() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'display_name','')); return new; end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.bootstrap_profile();
alter table profiles enable row level security; alter table classes enable row level security; alter table class_members enable row level security; alter table progress enable row level security; alter table teacher_comments enable row level security;
drop policy if exists profile_read_self_or_class_teacher on profiles;
create policy profile_read_self_or_class_teacher on profiles for select using(id=auth.uid() or exists(select 1 from class_members m join classes c on c.id=m.class_id where m.student_id=profiles.id and c.teacher_id=auth.uid()));
drop policy if exists profile_update_self on profiles;
create policy profile_update_self on profiles for update using(id=auth.uid()) with check(id=auth.uid());
revoke update on public.profiles from authenticated;
grant update(display_name) on public.profiles to authenticated;
drop policy if exists class_read_member on classes;
create policy class_read_member on classes for select using(teacher_id=auth.uid() or exists(select 1 from class_members where class_id=classes.id and student_id=auth.uid()));
drop policy if exists member_read_self_or_teacher on class_members;
create policy member_read_self_or_teacher on class_members for select using(student_id=auth.uid() or is_teacher_of(class_id));
drop policy if exists progress_read_owner_or_teacher on progress;
create policy progress_read_owner_or_teacher on progress for select using(student_id=auth.uid() or exists(select 1 from class_members m join classes c on c.id=m.class_id where m.student_id=progress.student_id and c.teacher_id=auth.uid()));
drop policy if exists progress_write_owner on progress;
create policy progress_write_owner on progress for insert with check(student_id=auth.uid());
drop policy if exists progress_update_owner on progress;
create policy progress_update_owner on progress for update using(student_id=auth.uid()) with check(student_id=auth.uid());
drop policy if exists progress_delete_owner on progress;
create policy progress_delete_owner on progress for delete using(student_id=auth.uid());
drop policy if exists comments_read_student_or_teacher on teacher_comments;
create policy comments_read_student_or_teacher on teacher_comments for select using(student_id=auth.uid() or teacher_id=auth.uid());
drop policy if exists comments_teacher_write on teacher_comments;
create policy comments_teacher_write on teacher_comments for all using(teacher_id=auth.uid() and is_teacher_of(class_id)) with check(teacher_id=auth.uid() and is_teacher_of(class_id));
grant select on public.profiles,public.classes,public.class_members,public.progress,public.teacher_comments to authenticated;
grant insert,update,delete on public.progress to authenticated;
grant insert,update,delete on public.teacher_comments to authenticated;
revoke all on public.profiles,public.classes,public.class_members,public.progress,public.teacher_comments from anon;
revoke all on function public.create_class(text,text),public.join_class(text),public.join_class_by_code(text),public.class_leaderboard(uuid),public.teacher_class_progress(uuid),public.save_student_progress(jsonb,bigint,timestamptz) from public,anon;
grant execute on function public.create_class(text,text),public.join_class(text),public.join_class_by_code(text),public.class_leaderboard(uuid),public.teacher_class_progress(uuid),public.save_student_progress(jsonb,bigint,timestamptz) to authenticated;
